export function getRandomUser() {
    const firstName = usersList[~~(Math.random() * usersList.length)]
    const lastName = usersList[~~(Math.random() * usersList.length)]
    const username = firstName + lastName + ~~(Math.random() * 1e3)
    return {
        firstName: firstName,
        lastName: lastName,
        username: username.toLowerCase(),
        fullName: firstName + ' ' + lastName,
    }
}

let usersList = [
    'Aarushi',
    'Abagael',
    'Abagail',
    'Abbey',
    'Abbi',
    'Abbie',
    'Abby',
    'Abdulmalik',
    'Abeja',
    'Abercrombie',
    'Abeyta',
    'Abi',
    'Abia',
    'Abigail',
    'Abree',
    'Abrianna',
    'Abrielle',
    'Abromaitis',
    'Aby',
    'Acacia',
    'Ada',
    'Adalia',
    'Adaline',
    'Adalyn',
    'Adams',
    'Adda',
    'Addie',
    'Addilyn',
    'Addison',
    'Adel',
    'Adela',
    'Adelaide',
    'Adele',
    'Adelene',
    'Adelia',
    'Adelina',
    'Adeline',
    'Adelle',
    'Adelynn',
    'Adena',
    'Adi',
    'Adina',
    'Adora',
    'Adoree',
    'Adrea',
    'Adreanna',
    'Adria',
    'Adriana',
    'Adrianna',
    'Adrianne',
    'Adrien',
    'Adrienne',
    'Ady',
    'Aerona',
    'Agatha',
    'Aggie',
    'Aggy',
    'Agnes',
    'Agnesse',
    'Agnus',
    'Ahlers',
    'Aida',
    'Aidonidis',
    'Aila',
    'Ailee',
    'Aileen',
    'Ailis',
    'Ailsa',
    'Ailsun',
    'Aimee',
    'Aine',
    'Ainsleigh',
    'Ainsley',
    'Aisha',
    'Aisling',
    'Aislinn',
    'Aislynn',
    'Aitchison',
    'Akerley',
    'Akilah',
    'Alaina',
    'Alana',
    'Alane',
    'Alanis',
    'Alanna',
    'Alannah',
    'Alasia',
    'Alaska',
    'Alayah',
    'Alayna',
    'Alayne',
    'Alba',
    'Albany',
    'Alberta',
    'Zyana',
]